version: '3'

services:
  graphql-srv:
    build:
      context: ./
    volumes:
      - .:/go/src/graphql-srv:rw
    ports:
      - 8080:8080
    # environment: do we need it here?
    depends_on:
      - backend-mysql
      - backend-redis
    networks:
      - backend

  backend-mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql

    environment:
      MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # container_name: gin-graphql-srv-mysql
    networks:
      - backend

  backend-redis:
    image: redis
    # container_name: gin-graphql-srv-redis
    ports:
      - 6379:6379
    volumes:
      - redis-vol:/data
    # restart: always
    command: redis-server
    networks:
      - backend

volumes:
  mysql-vol:
  redis-vol:

networks:
  backend:
    driver: bridge

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
